# Generated by Django 4.1.4 on 2023-09-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
                ('cost_per_day', models.CharField(max_length=10)),
                ('car_image', models.ImageField(upload_to='car_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('address', models.TextField()),
                ('date', models.DateTimeField()),
                ('to', models.DateTimeField()),
                ('car_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ST_App.car')),
            ],
        ),
    ]
