# Generated by Django 4.1.4 on 2023-09-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_booking',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
