# Generated by Django 4.1.4 on 2023-09-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ST_App', '0002_alter_user_booking_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_booking',
            old_name='car_names',
            new_name='car_name',
        ),
    ]
