# Generated by Django 4.1.4 on 2023-09-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ST_App', '0003_rename_car_names_user_booking_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cost_for_outstation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
